GET http://localhost:80/api/item?id=999
Accept: application/json
###

POST https://httpbin.org/post
Content-Type: application/json

{
  "id": 999,
  "value": "content"
}

###
POST https://httpbin.org/post
Content-Type: application/x-www-form-urlencoded

id=999&value=content
