### GET request with a header
// returns from and to as unix time stamp (time in milliseconds from january 1st 1970 to now)
// seems to be https://s-varaukset.fi/api/recommendations/slot/{restaurant_id}/{current_date}/{time}/{amount_of_eaters}
GET https://s-varaukset.fi/api/recommendations/slot/281/2022-08-12/1000/1
Accept: application/json

###
GET https://s-varaukset.fi/api/recommendations/slot/281/2022-08-12/1700/1
Accept: application/json


###
GET https://s-varaukset.fi/api/recommendations/slot/281/2022-08-12/2145/1
Accept: application/json
###

GET https://s-varaukset.fi/api/recommendations/slot/281/2022-08-12/2400/1
Accept: application/json

###
GET https://s-varaukset.fi/api/recommendations/slot/281/2022-08-12/0000/1
Accept: application/json

###

// testing.
GET https://s-varaukset.fi/api/recommendations/slot/38/2022-08-12/0800/1
Accept: application/json